name: CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  dotnet_versions: |
                   8.0.x
                   9.0.x

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{env.dotnet_versions}}

      - name: Clean nuget
        run: dotnet nuget locals all --clear
      - name: Build
        run: dotnet build -c Release
      #- name: Test
      #  if: success()
      #  run: dotnet test -c Release --no-build


  cd:
    name: CD
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{env.dotnet_versions}}

      - name: Install Versionize
        run: dotnet tool install --global Versionize

      - name: Setup git
        run: |
          git config --global user.email opencommissioning@spiratec.com
          git config --global user.name "oc-bot"

      - name: Versioning
        id: versionize
        run: versionize --exit-insignificant-commits
        continue-on-error: true

      - name: Get current version
        if: steps.versionize.outcome == 'success'
        run: echo "VERSION=$(versionize inspect)" >> $GITHUB_ENV

      - name: Get current changelog
        if: steps.versionize.outcome == 'success'
        run: echo "$(versionize changelog)" > latest_changelog.md

      - name: Push changes to GitHub
        if: steps.versionize.outcome == 'success'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

      - name: Build package
        run: dotnet build -c release

      - name: Publish new release
        if: steps.versionize.outcome == 'success'
        run: |
          gh release create v${{env.VERSION}} -t "Release v${{env.VERSION}}" -F latest_changelog.md
          gh release upload v${{env.VERSION}} "/home/runner/work/OC_TcPnScanner/OC_TcPnScanner/src/dsian.TcPnScanner.CLI/bin/Release/dsian.TcPnScanner.CLI.${{env.VERSION}}.nupkg"
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
