name: CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  dotnet_versions: |
                   6.0.x
                   7.0.x

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{env.dotnet_versions}}

      - name: Clean nuget
        run: dotnet nuget locals all --clear
      - name: Build
        run: dotnet build -c Release
      - name: Test
        if: success()
        run: dotnet test -c Release --no-build


  cd:
    name: CD
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{env.dotnet_versions}}

      - name: Clean nuget
        run: dotnet nuget locals all --clear
      - name: Build
        run: dotnet build -c Release

      - name: publish on version change
        id: publish_nuget
        if: ${{ success() && (github.event_name == 'push' && github.ref == 'refs/heads/main')}}
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: src/dsian.TcPnScanner.CLI/dsian.TcPnScanner.CLI.csproj
          NUGET_KEY: ${{secrets.TCHAXX_NUGET_API_KEY}}
