name: CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
                          6.0.x
                          7.0.x
      - name: Clean nuget
        run: dotnet nuget locals all --clear
      - name: Build
        run: dotnet build -c Release
      - name: Test
        if: success()
        run: dotnet test -c Release --no-build


  cd:
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
                          6.0.x
                          7.0.x

      - name: Clean nuget
        run: dotnet nuget locals all --clear
      - name: Build
        run: dotnet build -c Release

      # - name: publish on version change
      #   id: publish_nuget_mock
      #   if: ${{ success() && (github.event_name == 'push' && github.ref == 'refs/heads/main')}}
      #   uses: alirezanet/publish-nuget@v3.0.4
      #   with:
      #     PROJECT_FILE_PATH: src/dsian.TwinCAT.Ads.Server.Mock/dsian.TwinCAT.Ads.Server.Mock.csproj
      #     NUGET_KEY: ${{secrets.NUGET_API_KEY}}
