name: CD
on:
  push:
    branches: [ "main" ]

env:
  dotnet_versions: |
                   8.0.x
                   9.0.x

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{env.dotnet_versions}}

      - name: Install Versionize
        run: dotnet tool install --global Versionize

      - name: Setup git
        run: |
          git config --global user.email opencommissioning@spiratec.com
          git config --global user.name "oc-bot"

      - name: Versioning
        id: versionize
        run: versionize --exit-insignificant-commits

      - name: Get current version
        run: echo "VERSION=$(versionize inspect)" >> $GITHUB_ENV

      - name: Get current changelog
        run: echo "$(versionize changelog)" > latest_changelog.md

      - name: Dotnet build
        run: dotnet build --configuration release

      - name: Push to NuGet
        run: dotnet nuget push "/home/runner/work/OC_TcPnScanner/OC_TcPnScanner/src/dsian.TcPnScanner.CLI/bin/Release/OC.TcPnScanner.CLI.${{env.VERSION}}.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json

      - name: Push changes to GitHub
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

      - name: Publish new release
        run: |
          gh release create v${{env.VERSION}} -t "Release v${{env.VERSION}}" -F latest_changelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
